
#preload = /home/toska/Photos/yoru.png
#wallpaper = DP-2,/home/toska/Photos/yoru.png
#wallpaper = DP-3,/home/toska/Photos/yoru.png

preload = /home/remi/Pictures/gruvbox_girl.png
wallpaper = DP-1,/home/remi/Pictures/gruvbox_girl.png
wallpaper = DP-2,/home/remi/Pictures/gruvbox_girl.png

splash = true
